[reload]
command:/usr/local/opnsense/scripts/NetworkProvisioner/reload.php
parameters:
type:script
message:Reloading network interfaces for Network Provisioner
description:Reload Network Interfaces natively
